# ==================== 数据库配置 ====================
# MongoDB 连接URI
db-connection-uri = "mongodb://localhost:27017/"

# 数据库连接池最大连接数
db-connection-max = 10

# ==================== 视频处理配置 ====================
# 视频输出速度（FPS）
video-speed = 25

# 视频输出宽度
video-width = 640

# 视频输出高度
video-height = 480

# 封面图片宽度
cover-width = 320

# 封面图片高度
cover-height = 240

# ==================== 实时流配置 ====================
# 帧间隔（秒），控制实时流的帧率
frames-interval = 0.033  # 约30fps

# ==================== 文件清理配置 ====================
# 定时删除文件的间隔（秒）
remove-interval = 300  # 每5分钟清理一次