# ==================== 设备与种子配置 ====================
device = "cpu"
seed = 42

# ==================== 训练超参数 ====================
learning-rate = 0.00006
batch-size = 64
group-size = 10
num-epochs = 30
num-workers = 0
weight-decay = 0.0001

# ==================== 模型参数 ====================
alpha = 0.2
attention-window = 9
smoothing-window = 3

# ==================== 日志与检查点 ====================
log-interval = 10

load-checkpoint = false
load-checkpoint-path = 'checkpoints/best-ckpt4.pt'
best-checkpoint-path = 'checkpoints/best-ckpt4.pt'
last-checkpoint-path = 'checkpoints/last-ckpt4.pt'

# ==================== 数据集配置 ====================
# 数据集路径（预处理后的数据目录）
train-data-path = "D:\\Python\\dataprocess\\processed_data"

# 训练集划分比例（0.8表示80%训练，20%验证）
train-split = 0.8